apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    # Memory and disk management
    vm_memory_high_watermark.relative = 0.8
    disk_free_limit.absolute = 2GB
    
    # Heartbeat and connection settings
    heartbeat = 60
    consumer_timeout = 86400000
    
    # Clustering and management
    cluster_formation.peer_discovery_backend = classic_config
    management.tcp.port = 15672
    
    # Logging
    log.console = true
    log.console.level = info
    
    # Performance tuning
    channel_max = 2047
    connection_max = 1000
    
    # Prevent forced connection closure
    collect_statistics_interval = 5000