apiVersion: v1
data:
  MQ_HOST: cmFiYml0bXE=
  MQ_PASSWORD: Z3Vlc3Q=
  MQ_PORT: NTY3Mg==
  MQ_USER: Z3Vlc3Q=
  NR_FEEDS_ENDPOINT: cHVibGljZGF0YWZlZWRzLm5ldHdvcmtyYWlsLmNvLnVrOjYxNjE4
  NR_FEEDS_PASSWORD: c3Jqd2tVIUp1Y05BYjVy
  NR_FEEDS_USERNAME: ampiZGV2MjFAZ21haWwuY29t
kind: Secret
metadata:
  name: secrets
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: management
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuer
  template:
    metadata:
      labels:
        app: queuer
    spec:
      containers:
      - env:
        - name: MQ_HOST
          value: rabbitmq
        - name: MQ_PORT
          value: "5672"
        - name: MQ_USER
          valueFrom:
            secretKeyRef:
              key: MQ_USER
              name: secrets
        - name: MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MQ_PASSWORD
              name: secrets
        envFrom:
        - secretRef:
            name: secrets
        image: queuer:dev
        imagePullPolicy: IfNotPresent
        name: queuer
        ports:
        - containerPort: 3000
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |
          until nc -z rabbitmq 5672 >/dev/null 2>&1; do
            echo "waiting for rabbitmq AMQP port..."
            sleep 2
          done
        image: busybox:1.35
        name: wait-for-rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 5
          periodSeconds: 3
          tcpSocket:
            port: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - args:
        - redis-server
        - --save
        - ""
        - --appendonly
        - "no"
        image: redis:7-alpine
        name: redis
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trust-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trust-consumer
  template:
    metadata:
      labels:
        app: trust-consumer
    spec:
      containers:
      - env:
        - name: MQ_HOST
          value: rabbitmq
        - name: MQ_PORT
          value: "5672"
        - name: REDIS_ADDR
          value: redis:6379
        - name: MQ_USER
          valueFrom:
            secretKeyRef:
              key: MQ_USER
              name: secrets
        - name: MQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MQ_PASSWORD
              name: secrets
        envFrom:
        - secretRef:
            name: secrets
        image: trust-consumer:dev
        imagePullPolicy: IfNotPresent
        name: trust-consumer
        ports:
        - containerPort: 3000
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |
          until redis-cli -h redis ping >/dev/null 2>&1; do
            echo "waiting for redis..."
            sleep 2
          done
        image: redis:7-alpine
        name: wait-for-redis
      - command:
        - /bin/sh
        - -c
        - |
          until nc -z rabbitmq 5672 >/dev/null 2>&1; do
            echo "waiting for rabbitmq AMQP port..."
            sleep 2
          done
        image: busybox:1.35
        name: wait-for-rabbitmq
