apiVersion: apps/v1
kind: Deployment
metadata:
  name: vstp-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vstp-consumer
  template:
    metadata:
      labels:
        app: vstp-consumer
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              until pg_isready -h postgres -U postgres -d gbr_engine >/dev/null 2>&1; do
                echo "waiting for postgres to be ready..."
                sleep 2
              done
              echo "postgres is ready!"
        - name: wait-for-rabbitmq
          image: curlimages/curl:8.4.0
          command:
            - /bin/sh
            - -c
            - |
              until curl -f -u guest:guest http://rabbitmq:15672/api/aliveness-test/%2F 2>/dev/null; do
                echo "waiting for rabbitmq to be ready..."
                sleep 2
              done
              echo "rabbitmq health check passed!"
              # Additional wait to ensure AMQP is ready
              sleep 10
              echo "rabbitmq should be fully ready now!"
      containers:
        - name: vstp-consumer
          image: vstp-consumer
          env:
            - name: MQ_HOST
              value: rabbitmq
            - name: MQ_PORT
              value: "5672"
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQ_USER
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQ_PASSWORD
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: gbr_engine
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: POSTGRES_PASSWORD
          envFrom:
            - secretRef:
                name: secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
