apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuer
  template:
    metadata:
      labels:
        app: queuer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox
          command:
            - /bin/sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "waiting for rabbitmq..."
                sleep 2
              done
      containers:
        - name: queuer
          image: queuer:dev
          ports:
            - containerPort: 3000
          env:
            - name: MQ_HOST
              value: rabbitmq
            - name: MQ_PORT
              value: "5672"
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQ_USER
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQ_PASSWORD
          # Pull all env vars from the 'secrets' Secret (stringData) created by skaffold
          envFrom:
            - secretRef:
                name: secrets
