apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queuer
  template:
    metadata:
      labels:
        app: queuer
    spec:
      initContainers:
        - name: wait-for-rabbitmq
          image: curlimages/curl:8.4.0
          command:
            - /bin/sh
            - -c
            - |
              until curl -f -u guest:guest http://rabbitmq:15672/api/aliveness-test/%2F 2>/dev/null; do
                echo "waiting for rabbitmq to be ready..."
                sleep 2
              done
              echo "rabbitmq is ready!"
      containers:
        - name: queuer
          image: queuer:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MQ_HOST
              value: rabbitmq
            - name: MQ_PORT
              value: "5672"
            - name: MQ_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQ_USER
            - name: MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: MQ_PASSWORD
          envFrom:
            - secretRef:
                name: secrets
