apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - queuer/deployment.yaml
  - trust-consumer/deployment.yaml
  - vstp-consumer/deployment.yaml
  - data-fetcher/deployment.yaml
  - schedule-initializer/job.yaml
  - http-api/deployment.yaml
  - http-api/service.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml
  - rabbitmq/configmap.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - postgres/deployment.yaml
  - postgres/service.yaml

secretGenerator:
  - name: secrets
    envs:
      - ../../.env

configMapGenerator:
  - name: postgres-schema
    files:
      - schema.sql=../../schema.sql

generatorOptions:
  disableNameSuffixHash: true
