apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - queuer/deployment.yaml
  - rabbitmq/deployment.yaml
  - rabbitmq/service.yaml

secretGenerator:
  - name: secrets
    envs:
      - ../../.env

generatorOptions:
  disableNameSuffixHash: true
