// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Health check endpoint
	// (GET /health)
	GetHealth(c *fiber.Ctx) error
	// Get all locations
	// (GET /locations)
	GetLocations(c *fiber.Ctx) error
	// Get all operators
	// (GET /operators)
	GetOperators(c *fiber.Ctx) error
	// Get OpenAPI schema
	// (GET /schema)
	GetSchema(c *fiber.Ctx) error
	// Get a single service
	// (GET /service)
	GetService(c *fiber.Ctx, params GetServiceParams) error
	// Query services with filters
	// (POST /services)
	QueryServices(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// GetLocations operation middleware
func (siw *ServerInterfaceWrapper) GetLocations(c *fiber.Ctx) error {

	return siw.Handler.GetLocations(c)
}

// GetOperators operation middleware
func (siw *ServerInterfaceWrapper) GetOperators(c *fiber.Ctx) error {

	return siw.Handler.GetOperators(c)
}

// GetSchema operation middleware
func (siw *ServerInterfaceWrapper) GetSchema(c *fiber.Ctx) error {

	return siw.Handler.GetSchema(c)
}

// GetService operation middleware
func (siw *ServerInterfaceWrapper) GetService(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetServiceParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "uid" -------------

	err = runtime.BindQueryParameter("form", true, false, "uid", query, &params.Uid)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter uid: %w", err).Error())
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameter("form", true, false, "id", query, &params.Id)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Optional query parameter "date" -------------

	err = runtime.BindQueryParameter("form", true, false, "date", query, &params.Date)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter date: %w", err).Error())
	}

	return siw.Handler.GetService(c, params)
}

// QueryServices operation middleware
func (siw *ServerInterfaceWrapper) QueryServices(c *fiber.Ctx) error {

	return siw.Handler.QueryServices(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/locations", wrapper.GetLocations)

	router.Get(options.BaseURL+"/operators", wrapper.GetOperators)

	router.Get(options.BaseURL+"/schema", wrapper.GetSchema)

	router.Get(options.BaseURL+"/service", wrapper.GetService)

	router.Post(options.BaseURL+"/services", wrapper.QueryServices)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+Ra6W/bOBb/VwjtfkixTiNfaWpgP6RN280im2RjD6a7xUCgpWeJU4pUSSpTY+D/fcFD",
	"sg76SNMZFNh8si3yvd+7D+X3IOZ5wRkwJYPZ74GMM8ix+fhOCC4eQBacSdA/FIIXIBQB8xj0Y/PhK84L",
	"CsEsuMIKL7EEZJ8NArUu9O9SCcLSYDMIcpASp9C+9h4TCglSHMWcMYiV/pg4Wj4qUuH4c5uG4YiwQpQw",
	"QJMRIgxJEI8khpcp7xPZDAIBX0oiIAlmn4IKcIXvl/oCX/4KsdJcP0BOGJkzXMiMq75C3N0owQoiRXIj",
	"ZQIyFqRQhLNgFixIDlLhvEB8hVQGyNJE7ipSGVaoLDSFBGFKeYz1TRkMGqKOwtH0dBieDoeLcDobh7Mw",
	"/G8wCFZc5FgFs0DfPjX8PaoTIHkpYohSwcsiIonso3xwZ5A5g66vJDpRAhOGWJkvQcgXFTZrNZURWSlb",
	"691+r/TUgP4pGE4vLiZjrV6iIDe8exDdD1gIvDaG6lniH4Cpyna7plRYlbLtIJm5s/bp5BGENJI3zw9f",
	"hi/Dg37jOG1p+BznxpmxDzQWHZTzxaUP4aqkNGI47wTOXGEmtREuiSi4UDtihfGv7XsXr6aTie+wIgXl",
	"cRTzBNrAPmlkt5fXD8HAfJovbp9oxKbWWmxqiPtU955QBWKnAjtRlgF6+zBHmn4VaFUooROsKTGsyCNo",
	"57XMX7Qi7P7yyqedygB9btoNNHF94igON5wlnKF7nCSEpYqz/abrc9RGuPvoFbHF6ICp/cQX1/c3d2+f",
	"pb/F3a03eHoWvuXqPS9Z8qRCc8urfCPRSt8+MsH7XOyuAIEV9zkXTzoBd/Nun19sz30QgBUIdMlSSvBB",
	"cIaRo+ODeI9Twoz6r9mK94FSkhPVN+W/8FeSl7nL2tqStdIEqFIwSJpmm4Y1a8IUpCA0b75aSfAQv+0T",
	"lZ9JUbRpeknWzHtEL2NVYroPcF1fROUvByVQXGEaCZAlVb5soR/7WOZYxRlhqfH/LyWIdZPX0MesY1en",
	"u4EzUEPyLiqf1edxBklJYXf5wEZdERaCPGK6U53uOdI9AVoJnqPFw0/zBVoBJOiErBB+xITiJYV2GA8n",
	"M3/ucHwTKLBQpYCdnOsT38R76uW9FbZ9ejwLw5eh+Wt2Q7saIUcnolgBA+lxjBv3RLtcTlipTLIRtTpP",
	"Ci6JSYN/R5rKADFIsfsBsKDrlkhDn2+2VPgseWpK3yDR1kxPlGnkk4kkLWGGF8Pz0cQbmbTh2X8VsApm",
	"wV/OtvPImRtGzuoIaNyJuEigXRaG+3hE9lErm9/5FFlQrLS2OxbxHi2XlMTR93JJR+57+UQnGRGdddra",
	"aFigp1hvRrKp8d86Fz7AlxKkZwzS40ff9a6wMu3CyjRy2yS7XKOTUkJi/DADnOhaeMoZXSMJWMQZyBc7",
	"pp/uzONTaUWxD8h2lJp/faaVf968GvsINkrtCpdU2aJzdN1V3FWybtnK7R39RX8jzH4bHirJDkQPw62X",
	"t67Q6CQ8JSyBr5C86JTqGsQwbKHwNwaub4oO6bc6eLZwPWVL0R9+9oYClhJkpDLByzTbR72ekU2ZrqZQ",
	"ex9V9xuTSqdzqpx+VQ8YxyQiN46YNjqHSNe1PsZ3WFACUtnah5XtW7xdeuXUo/NFqOf5J430BoLi/nT/",
	"VPaj8Wz6ejZ9fSx7X0t/eIBvJ5JdjX9Rt72H7NJpkPXs5Lxe36xtv4+Eg1SjOTTD1gwGTZx7suZuOXGs",
	"yKNLy/61kWmZtseMSe0eybRQ9kEnnoPh+evXYfXnc5wYsxgo9TXiP2egMhCd1Y5E9RUdepih+eK++s0i",
	"ExBz0RjHlpxTwKZyp2bXFWVEKi7W/uXYqSk+kNTrI6lTmNuSNRZiplw0wQ2QqSKKo5IlIPRUampKbmHF",
	"GWYpSMQfjVCABC9NxTjKNzqbv55r1LK1t2ueDuxtKQQwVUkknrNpsyoAJGwlhgS5Ktjftw2C4fR8Ep4/",
	"ZWfTLp4Ntxr5K2O37QtfjSfjfR3ZE2KzOwl5wPLGGL+PVj3u6yTh6EYJXstIlKyzjTORM/TGTn0VWBJV",
	"Lc+3dik1MamwUM8nR1KGKSUsjTpG2dnWGKeLtJ+lLja3dz5+3H3Dt2m933287OL5z8XwYnzuv1BK5fD7",
	"sqENk+urvRlwNL6cTN+8PX91XHe8BdlVYiMYmg7cT/eaLnFLGkWUbXHePKB3LCUM0OX9dWNZXG2Zrfsy",
	"XJBgFozd4rnAKjOaPbOra/0x9W1iHkxDafsfexRZs1S7O8vUBogukYnGBMpu0c1WwlYmw20Uhnb3xRQw",
	"ww0XBSVW4rNfpS3GNpoOxVpnT2+U08Y+35aWakG/GQTT74ih/RbLA+GamX0mNXkVhHt3pc/JMs+xjgb3",
	"wgHFGcSfEbCk4IQpc+aslc322gcjSqTSRsGUNvpWs9GC5guvnqluGi+CnmWto9Lt7jTb196NE2mrhh/R",
	"fh9AtZVubVfVjKfazuYeZyWWIg0bMwISnSzu3soXx5j0rub9Z5i0WfWONelWOz+ySRsotUm3CA7myrsC",
	"2OX9NZIFxGTlRNk2lvoRYeif87tb10j6zDi3/J5pw25t6mmkxmqudHH9qPZpo3YGshn/iIiThKV0O9Iv",
	"1wiIHUpM+P10fYW4QFXvpFuBv1UdcN9MjqsuqwLnoEAH/adea1FTVtztn7SOW01F3bIQfaN6L2DfAQWu",
	"d9hp2EGX47wBv8UTneSlVGgJdrD5jajMSNfeKbsm2wfFj6TxquLAim65RidVh4R+y4ChUlsEkWSAuLmD",
	"qYVVkmTPjs6HzZlpi+5AT7v55Q/sUnqT/+42xb5r3AyCyZ8Zbm9wUg15lvfku/HuvX3dIzzjaquAH7Me",
	"dHJGK+PYlRKXe3JOnUt0B1+tDnQs+t8JFoI/kgQSFzGyl3jMfmu+XRQ5I77hyfp7e29rJ79pTzdKlLD5",
	"4wOovc3b7Ujy/zOM+v+z8COGkTHiFqjJ75V7bzabzf8CAAD//5vmqckwKAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
